name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

    