name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  ARCH: x86_64
  SITE: generic
  NAME: gmp
  SRC_URL: https://gmplib.org/download/gmp/
  SRC_DIR: ${{ vars.SRC_DIR }}
  SOFT_DIR: ${{ vars.SOFT_DIR }}
  REPO_DIR: ${{ vars.REPO_DIR }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 6.1.2
          - 6.2.1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: "bash build-gh.sh"
        env:
          SOURCE_FILE: "${{ env.NAME }}-${{ matrix.version }}.tar.bz2"
          VERSION: ${{ matrix.version }}
