name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  REPO_DIR: ${{ vars.REPO_DIR }}
  ARCH: x86_64
  SITE: generic
  NAME: gmp
  SRC_URL: https://gmplib.org/download/gmp/
  SRC_DIR: "${{ var.SRC_DIR }}"
  SOFT_DIR: "${{ var.SOFT_DIR }}"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 6.1.2
          - 6.2.1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: "bash build-gh.sh"
        env:
          SOURCE_FILE: "${NAME}-${VERSION}.tar.bz2"
